# Chạy: mvn spring-boot:run -Dspring-boot.run.profiles=mysql
# Database XAMPP MySQL: Hieuthuoc
spring.datasource.url=jdbc:mysql://localhost:3306/Hieuthuoc?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Ho_Chi_Minh&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
